Repository pagopa/pagopa-wallet-service, pull requests merged in 2023-05, with the labels that each got.

#23 Chk 1424 get wallet
  .env.example
  docker-compose.yml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/domain/PaymentInstrumentDetail.kt
  src/main/kotlin/it/pagopa/wallet/domain/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/CardDetailsTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/PaymentInstrumentDetailTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: enhancement, size/large

#18 [CHK-1434] feat(npg): add notification callback API
  build.gradle.kts
  npg-api/npg-notification-api.yaml
Labels: size/small

#24 [CHK-1435] Wallet Notify
  api-spec/wallet-api.yaml
  build.gradle.kts
  src/main/kotlin/it/pagopa/wallet/controllers/WalletNotifyController.kt
  src/main/kotlin/it/pagopa/wallet/domain/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/exception/ContractIdNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletNotifyControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/CardDetailsTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/large

#26 [CHK-1435] Notification url
  src/main/kotlin/it/pagopa/wallet/exception/ContractIdNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/exception/SecurityTokenMatchException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletNotifyControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small
