Repository pagopa/pagopa-wallet-service, pull requests merged in 2023-10, with the labels that each got.

#32 [CHK-1965] feat(audit): add `LoggedAction` monad
  src/main/kotlin/it/pagopa/wallet/audit/LoggedAction.kt
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/repositories/LoggingEventRepository.kt
  src/test/kotlin/it/pagopa/wallet/audit/LoggedActionTests.kt
Labels: size/small, patch, chart-patch

#33 [CHK-1961] Integrate service and audit in createWallet
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/wallet/audit/LoggedAction.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/Service.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/common/ServiceId.kt
  src/main/kotlin/it/pagopa/wallet/domain/common/ServiceName.kt
  src/main/kotlin/it/pagopa/wallet/domain/common/ServiceStatus.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/services/Service.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/UserId.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/document/services/ServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/document/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/services/ServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#36 [Chk-1961] feat(wallet): manage services assignmet to wallet
  api-spec/wallet-api.yaml
  build.gradle.kts
  gradle.lockfile
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/WalletDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#34 [CHK-1961] feat(service): implement controller + service to create new global service
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/controllers/ServicesController.kt
  src/main/kotlin/it/pagopa/wallet/documents/service/Service.kt
  src/main/kotlin/it/pagopa/wallet/services/ServicesService.kt
  src/test/kotlin/it/pagopa/wallet/ApplicationTest.kt
  src/test/kotlin/it/pagopa/wallet/ServiceTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/ServicesControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/ServicesServiceTest.kt
Labels: size/small

#35 feat(services): add API to change service status
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/controllers/ServicesController.kt
  src/main/kotlin/it/pagopa/wallet/exception/ServiceNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/services/ServicesService.kt
  src/test/kotlin/it/pagopa/wallet/ServiceTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/ServicesControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/ServicesServiceTest.kt
Labels: size/small

#37 fix: add missing @Document annotation on Service class
  src/main/kotlin/it/pagopa/wallet/documents/service/Service.kt
  src/test/kotlin/it/pagopa/wallet/ApplicationTest.kt
Labels: size/small

#38 fix paymentInstrument serialization in document
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
Labels: size/small

#39 [CHK-1961] Hot fix for dev testing
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
Labels: size/small

#40 [CHK-2000] feat(wallet): rename walletservice in applications
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Application.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Application.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/ApplicationTest.kt
Labels: size/small

#41 feat(docs): Add ddd annotations for aggregate root
  src/main/kotlin/it/pagopa/wallet/annotations/AggregateRoot.java
  src/main/kotlin/it/pagopa/wallet/annotations/AggregateRootId.java
  src/main/kotlin/it/pagopa/wallet/annotations/Entity.java
  src/main/kotlin/it/pagopa/wallet/annotations/ValueObject.java
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Application.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/ContractId.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/PaymentInstrumentId.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/PaymentMethodId.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/UserId.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletId.kt
Labels: size/small

#45 feat(wallet-session): CHK-2036 post wallet sessions
  .env.example
  .env.local
  api-spec/wallet-api.yaml
  docker-compose.yml
  docker/config/npg-mock/Dockerfile.npg-mock
  docker/config/npg-mock/middleware.js
  docker/config/npg-mock/npg-server.json
  docker/config/npg-mock/routes.json
  npg-api/npg-api.yaml
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletConflictStatusException.kt
  src/main/kotlin/it/pagopa/wallet/repositories/NpgSession.kt
  src/main/kotlin/it/pagopa/wallet/repositories/NpgSessionsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/repositories/RedisTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/ApplicationTest.kt
  src/test/resources/application.properties
Labels: size/large

#44 [Chk 2033] feat(wallet): get wallet business logic
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#46 feat: CHK-2038 added collection tests for CR pipeline
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  .env.example
  api-tests/wallet_local.collection.tests.json
  api-tests/wallet_local.environment.json
  docker/config/ecommerce-payment-methods/Dockerfile.ecommerce-payment-methods
Labels: size/large

#48 fix: CHK-2068 modified body for execute call to NPG for retrieve fields
  .env.example
  helm/values-dev.yaml
  npg-api/npg-api.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/config/SessionUrlConfig.kt
  src/main/kotlin/it/pagopa/wallet/repositories/NpgSession.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/ApplicationTest.kt
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/small
