Repository pagopa/pagopa-wallet-service, pull requests merged in 2023-11, with the labels that each got.

#49 [CHK-2057] feat added unique id generation
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/UniqueIdUtils.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/converters/mongo/UniqueIdUtilTest.kt
Labels: size/small

#51 [CHK-2092] hotfix for wallet
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/Bin.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/ExpiryDate.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/MaskedPan.kt
  src/main/kotlin/it/pagopa/wallet/exception/SessionNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/BinTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetailsTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/ExpiryDateTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/MaskedPanTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#52 [CHK-2094] Configuration
  helm/values-dev.yaml
Labels: size/small

#55 [CHK-2098] post wallet response
  api-tests/wallet_local.collection.tests.json
  helm/values-dev.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
Labels: size/large

#56 [CHK-2069] Add postman test
  .env.example
  api-tests/wallet_local.collection.tests.json
  api-tests/wallet_local.environment.json
  docker/config/npg-mock/npg-server.json
Labels: size/large

#58 [CHK-2097] feat: added redis configuration and new document
  src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/exception/UniqueIdGenerationException.kt
  src/main/kotlin/it/pagopa/wallet/repositories/RedisTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/repositories/UniqueIdDocument.kt
  src/main/kotlin/it/pagopa/wallet/repositories/UniqueIdTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/UniqueIdUtils.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/converters/mongo/UniqueIdUtilTest.kt
Labels: size/small

#57 feat(deploy): CHK-2078 uat deploy pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/deploy-pipelines.yml
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/large, patch, chart-patch

#60 fix(conf): remove trailing slash from `SESSION_URL_BASEPATH` env variable
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small

#59 [CHK-2067] add api tests
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
Labels: size/small

#63 [CHK-2125] add wallet id to the response
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
Labels: size/small

#62 CHK-2164: feat: added new api POST wallet/:walletId/session/:orderId/notifications
  .env.example
  .env.local
  api-spec/wallet-api.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletSecurityTokenNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/audit/LoggedActionTests.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/document/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#65 feat: CHK-2170 add find session wallet
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small
