Repository pagopa/pagopa-wallet-service, pull requests merged in 2023-12, with the labels that each got.

#69 feat: saved contract id into collection
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#71 feat: differentiate redirect url for payment method apm
  .env.example
  .env.local
  README.md
  docker/config/ecommerce-payment-methods/payment-method-server.json
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/config/OnboardingReturnUrlConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/WalletDetailsType.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/ServicesControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#73 fix: env local and env example
  .env.example
  .env.local
Labels: size/small

#74 fix: added retryWrites=false into mongo uri
  src/main/resources/application.properties
Labels: size/small

#75 fix: remove detail error response
  api-tests/wallet_local.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
Labels: size/large, patch, chart-patch

#78 fix: junit tests
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
Labels: size/small

#70 [CHK-2177] refactor(api): move `PATCH /wallet/{id}` -> `PUT /wallet/{id}/services`
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/services/ServiceStatus.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletServiceStatusConflictException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletServiceUpdateData.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/services/ServiceStatusTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#72 [CHK-2238] refactor(api): return redirection url instead of form fields when creating session for APMs
  .env.example
  README.md
  api-spec/wallet-api.yaml
  build.gradle.kts
  helm/values-dev.yaml
  helm/values-uat.yaml
  npg-api/npg-api.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/config/OnboardingConfig.kt
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/PayPalDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/MaskedEmail.kt
  src/main/kotlin/it/pagopa/wallet/domain/details/PayPalDetails.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/large, patch, chart-patch

#76 fix: add detail for APM notify
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/exception/InvalidRequestException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/resources/logback-spring.xml
Labels: size/small

#79 Chk 2248 update api tests
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_cards.environment.json
  api-tests/wallet_local_paypal.collection.tests.json
  api-tests/wallet_local_paypal.environment.json
  docker/config/npg-mock/middleware.js
  docker/config/npg-mock/npg-server.json
  docker/config/npg-mock/routes.json
Labels: size/large

#80 Code refactoring
  src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
Labels: size/small, patch, chart-patch

#81 fix(helm): fix creditcard route to lowercase
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#82 fix(api-test): differentiate test result exported files
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
Labels: size/small

#83 [CHK-2258] feat(auth-data): add support for returning wallet auth data for APMs
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, patch, chart-patch
