Repository pagopa/pagopa-wallet-service, pull requests merged in 2023-04, with the labels that each got.

#2 [CHK-1379] Dev Code-Review and Deploy pipelines
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .devops/performance-test-pipelines.yml
  .github/auto_assign.yml
  .github/release.yml
  .github/workflows/anchore.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/self_hosted.yml
  .github/workflows/update_code.yml
  .github/workflows/update_infra.yml
  .gitignore
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  settings.gradle
Labels: size/small

#3 fix build configuration
  .java-version
  .pre-commit-config.yaml
  api-spec/wallet-api.yaml
  build.gradle
  gradlew
  npg-api/npg-api.yaml
  openapi/generate_openapi.sh
  settings.gradle
Labels: bug, size/large

#7 CHK-1400-add-check-pr-size
  .github/workflows/check_pr.yml
Labels: size/small

#9 Chk 1381 add npg client
  .env.example
  helm/values-dev.yaml
  npg-api/npg-api.yaml
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/wallet/exception/ApiError.kt
  src/main/kotlin/it/pagopa/wallet/exception/NpgClientException.kt
  src/main/kotlin/it/pagopa/wallet/exception/RestApiException.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/config/WebClientConfigTest.kt
  src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
  src/test/resources/application.properties
Labels: enhancement, size/large

#11 fix: add semantic versioning plugin
  build.gradle.kts
Labels: enhancement, size/small

#10 [CHK-1383] feat(api): implement wallet creation endpoint
  .env.example
  .gitignore
  Dockerfile
  README.md
  api-spec/wallet-api.yaml
  build.gradle.kts
  docker-compose.yml
  docker/config/.env
  docker/config/cosmosdb.sh
  docker/config/mongo/mongo-express.env
  docker/config/mongo/mongodb.env
  docker/docker-compose.yml
  src/main/kotlin/it/pagopa/wallet/config/MongoConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/controller/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/domain/PaymentInstrument.kt
  src/main/kotlin/it/pagopa/wallet/domain/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/exception/BadGatewayException.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/converters/mongo/PaymentInstrumentIdConverters.kt
  src/main/kotlin/it/pagopa/wallet/util/converters/mongo/WalletIdConverters.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/PaymentInstrumentTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/converters/mongo/PaymentInstrumentIdConvertersTest.kt
  src/test/kotlin/it/pagopa/wallet/util/converters/mongo/WalletIdConvertersTest.kt
  src/test/resources/application.properties
Labels: size/large

#12 fix(deploy): fix deploy vars
  helm/values-dev.yaml
Labels: size/small

#13 fix: add error response log
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
Labels: enhancement, size/small

#14 fix(npg): fix request to NPG HPP API
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
Labels: size/small

#17 fix: update docker base image to amazon-corretto
  Dockerfile
Labels: bug, size/small

#16 [CHK-1417] - dependency lock and verification
  Dockerfile
  README.md
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
Labels: enhancement, size/large

#20 [CHK-1423] feat: add problem json responses
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
Labels: enhancement

#19 [CHK-1423]: Update wallet specs
  api-spec/wallet-api.yaml
  build.gradle.kts
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/exception/InternalServerErrorException.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: enhancement, size/large

#25 feat: use wallet openapi generated enums
  src/main/kotlin/it/pagopa/wallet/domain/PaymentInstrumentType.kt
  src/main/kotlin/it/pagopa/wallet/domain/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/WalletServiceEnum.kt
  src/main/kotlin/it/pagopa/wallet/domain/WalletStatus.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/domain/WalletTest.kt
Labels: enhancement, size/small
