Repository pagopa/pagopa-wallet-service, pull requests merged in 2024-03, with the labels that each got.

#96 [CHK-2524] Migration first API implementation
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .env.example
  api-tests/wallet_local_migration.collection.tests.json
  api-tests/wallet_local_migration.environment.json
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/config/WalletMigrationConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/documents/migration/WalletPaymentManagerDocument.kt
  src/main/kotlin/it/pagopa/wallet/domain/migration/WalletPaymentManager.kt
  src/main/kotlin/it/pagopa/wallet/domain/migration/WalletPaymentManagerRepository.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletPaymentManagerRepositoryImpl.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/large

#101 [CHK-2561] feat(wallet): add implementation for logical deletion of wallets
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, patch, chart-patch

#98 [CHK-2555] Card details refactoring
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/ExpiryDate.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/LastFourDigits.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/MaskedPan.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetailsTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/ExpiryDateTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/LastFourDigitsTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/MaskedPanTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor

#99 [CHK-2567] (wallet: feat) : rename service in application
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_paypal.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletApplicationUpdateData.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/document/services/ServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/document/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/large

#100 feat: add logo url for wallet response
  .env.example
  README.md
  api-spec/wallet-api.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/config/LogoConfig.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/WalletUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/config/LogoConfigTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/WalletUtilsTest.kt
  src/test/resources/application.test.properties
Labels: size/small

#104 fix(helm): add wallet logo mapping for green uat env values
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#106 [CHK-2580] Update fields for update card details migration api
  api-spec/wallet-api.yaml
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
Labels: size/small

#105 [CHK-2582] - Migration - API update wallet details
  api-tests/wallet_local_migration.collection.tests.json
  api-tests/wallet_local_migration.environment.json
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/domain/migration/WalletPaymentManagerRepository.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletId.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/Bin.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/ExpiryDate.kt
  src/main/kotlin/it/pagopa/wallet/exception/MigrationError.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletPaymentManagerRepositoryImpl.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
Labels: size/small

#108 [CHK-2585] Migration OpenAPI delete wallet
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
Labels: size/small

#110 chore(ci): converted tests steps into separated jobs
  .devops/deploy-pipelines.yml
Labels: size/small

#111 [CHK-2587] Migration delete wallet implementation
  api-tests/wallet_local_migration.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
Labels: size/small

#109 [CHK-2378] Applications in wallet
  .env.example
  .env.local
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_paypal.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/documents/applications/Application.kt
  src/main/kotlin/it/pagopa/wallet/exception/ApplicationNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/large, chart-minor, minor

#112 [CHK-2582] fix: remove usage of newContractIdentifier as join key
  api-spec/wallet-api.yaml
  api-tests/wallet_local_migration.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
Labels: size/small

#114 [CHK-2468] fix(npg): remove url decoding of session id when creating wallet session
  src/main/kotlin/it/pagopa/wallet/repositories/NpgSessionsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, patch, chart-patch

#107 [CHK-2623] Add missing brands to openapi
  .env.example
  api-spec/wallet-api.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/config/LogoConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/config/LogoConfigTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetailsTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/WalletUtilsTest.kt
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#121 fix(config): fix wallet logo mapping uat
  helm/values-uat.yaml
Labels: size/small

#119 [CHK-2644] feat(migration): enable a default application for migrated wallets
  .env.example
  .env.local
  api-tests/wallet_local_migration.collection.tests.json
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/config/WalletMigrationConfig.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletApplicationMetadata.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/small, chart-minor, minor

#122 fix(npg): encoding of NPG session id
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
Labels: size/small

#116 feat(wallet-check): CHK-2636 idcard4 to already wallet check
  .env.example
  .env.local
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletNotificationProcessingResult.kt
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/Constants.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor

#117 feat: switch payment-wallets collections
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
Labels: size/small
