Repository pagopa/pagopa-wallet-service, pull requests merged in 2024-07, with the labels that each got.

#173 fix(migration): Return proper error code when trying to validate a deleted wallet
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/exception/MigrationError.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
Labels: size/small, patch

#172 [CHK-2888] feat(npg-client): add tcp keep alive configurations
  .env.example
  .env.local
  README.md
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#176 feat: make create session wallet idempotent
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_paypal.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletConflictStatusException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/large, chart-minor, minor

#174 fix(monitoring): [CHK-2981] Added custom span for NPG notifications
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/common/tracing/TracingUtils.kt
  src/main/kotlin/it/pagopa/wallet/common/tracing/WalletTracing.kt
  src/main/kotlin/it/pagopa/wallet/config/OpenTelemetryConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/controllers/common.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/exception/SecurityTokenMatchException.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletConflictStatusException.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/common/tracing/TracingUtilsTest.kt
  src/test/kotlin/it/pagopa/wallet/common/tracing/WalletTracingTest.kt
  src/test/kotlin/it/pagopa/wallet/config/OpenTelemetryTestConfiguration.kt
  src/test/kotlin/it/pagopa/wallet/controllers/ApplicationsControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/TransactionWalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandlerTest.kt
Labels: size/small

#177 fix(deploy): Reduced wallet min replicas
  helm/pay-wallet-values-prod.yaml
Labels: size/small, chart-patch

#178 fix: increased npg notification validity token to 15 minutes
  helm/pay-wallet-values-prod.yaml
Labels: size/small, major

#179 chore: trigger helm major bump
  helm/pay-wallet-values-dev.yaml
Labels: size/small, ignore-for-release, chart-major

#180 fix: [CHK-3051] Map status code for optimistic lock exception
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
Labels: size/small, patch, chart-patch
