Repository pagopa/pagopa-wallet-service, pull requests merged in 2024-06, with the labels that each got.

#143 [CHK-2846] feat(clients): add clients info in api spec and in wallet service response
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#144 feat [CHK-2878]: Get psp business name from Payment methods
  .env.example
  .env.local
  api-spec/wallet-api.yaml
  build.gradle.kts
  docker/config/ecommerce-payment-methods/Dockerfile.ecommerce-payment-methods
  docker/config/ecommerce-payment-methods/middleware.js
  docker/config/ecommerce-payment-methods/payment-method-server.json
  docker/config/ecommerce-payment-methods/routes.json
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/client/PspDetailClient.kt
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/wallet/config/properties/PaymentMethodsConfigProperties.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/PayPalDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/PayPalDetails.kt
  src/main/kotlin/it/pagopa/wallet/exception/PspNotFoundException.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/client/PspDetailClientTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#146 fix(conf-NPG-urls): update cancel url to outcome ones
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#147 [CHK-2886] implementation tuning
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
Labels: size/small, patch, chart-patch

#149 feat(helm-values): CHK-2948 add conf for pay-wallet nodepool
  helm/values-pay-wallet-dev.yaml
  helm/values-pay-wallet-uat.yaml
Labels: size/small

#148 feat: [CHK-2944] Wallet creation timeout event producer
  .env.example
  .env.local
  README.md
  azurite/Dockerfile
  azurite/create-queues.sh
  build.gradle.kts
  docker-compose.yml
  gradle.lockfile
  gradle/verification-metadata.xml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/audit/WalletCreatedEvent.kt
  src/main/kotlin/it/pagopa/wallet/client/WalletQueueClient.kt
  src/main/kotlin/it/pagopa/wallet/common/QueueEvent.kt
  src/main/kotlin/it/pagopa/wallet/common/serialization/WalletEventMixin.kt
  src/main/kotlin/it/pagopa/wallet/common/tracing/QueueTracingInfo.kt
  src/main/kotlin/it/pagopa/wallet/common/tracing/Tracing.kt
  src/main/kotlin/it/pagopa/wallet/common/tracing/TracingUtils.kt
  src/main/kotlin/it/pagopa/wallet/config/AzureStorageConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/config/OpenTelemetryConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/config/SerializationConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/config/properties/ExpirationQueueConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/LoggingEventDispatcher.kt
  src/main/kotlin/it/pagopa/wallet/repositories/LoggingEventRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/LoggingEventDispatcherService.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/audit/LoggedActionTests.kt
  src/test/kotlin/it/pagopa/wallet/client/WalletQueueClientTest.kt
  src/test/kotlin/it/pagopa/wallet/common/serialization/WalletEventTest.kt
  src/test/kotlin/it/pagopa/wallet/common/tracing/TracingUtilsTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/LoggingEventDispatcherServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/AzureQueueTestUtils.kt
  src/test/resources/application.test.properties
Labels: size/large, chart-minor, minor

#151 feat: add pipeline for prod env
  .devops/pay-wallet-deploy-pipelines.yml
  helm/values-pay-wallet-prod.yaml
Labels: size/large

#152 fix: serialize non null fields
  src/main/kotlin/it/pagopa/wallet/config/SerializationConfiguration.kt
  src/main/resources/application.properties
Labels: size/small

#150 feat: add openapi to patch wallet status
  README.md
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_paypal.collection.tests.json
  build.gradle.kts
  src/main/kotlin/it/pagopa/wallet/common/tracing/Tracing.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/exception/WalletConflictStatusException.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/EitherExtension.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/config/SerializationConfigurationTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/large

#153 chore(helm-itn): align values
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, patch, chart-patch

#154 fix(helm-itn): queue names
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, patch, chart-patch

#156 Itn helm values alignment
  helm/pay-wallet-values-uat.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#157 fix: [CHK-2961] increase wallet resource
  helm/values-uat.yaml
Labels: size/small

#159 chore(weu to itn): disable all weu pipelines and helm values
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/large, ignore-for-release

#158 fix: [CHK-2961] Increase wallet resource
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, chart-patch

#160 fix: update OTeL endpoint for prod
  helm/pay-wallet-values-prod.yaml
Labels: size/small, patch, chart-patch

#161 feat(helm): [CHK-2971] add blue deployment
  .devops/pay-wallet-deploy-pipelines.yml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, chart-minor

#162 fix: prod config for npg
  helm/pay-wallet-values-prod.yaml
Labels: size/small

#164 fix(ingress): remove .prod for ingress domain
  helm/pay-wallet-values-prod.yaml
Labels: size/small

#166 Chk 2979 npg correlation
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, patch, chart-patch

#163 fix(migration): optimized find wallet on migration by searching for directly for contract
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
Labels: size/small

#169 fix(migration): Conflict status for already onboarded wallet
  api-spec/wallet-api.yaml
  api-tests/wallet_local_migration.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
Labels: size/small

#168 feat: generate session token for onboarding
  .env.example
  .env.local
  docker-compose.yml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/JwtTokenUtils.kt
  src/main/kotlin/it/pagopa/wallet/util/TransactionId.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/JwtTokenUtilsTest.kt
  src/test/kotlin/it/pagopa/wallet/util/TransactionIdTest.kt
Labels: size/small, chart-minor, minor

#167 feat: [CHK-2982] Added npg client tracing
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/common/tracing/TracingUtils.kt
  src/main/kotlin/it/pagopa/wallet/services/LoggingEventDispatcherService.kt
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/common/tracing/TracingUtilsTest.kt
  src/test/kotlin/it/pagopa/wallet/services/LoggingEventDispatcherServiceTest.kt
Labels: size/small, chart-minor, minor

#170 feat: wallet controller warmup
  src/main/kotlin/it/pagopa/wallet/controllers/TransactionWalletController.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/warmup/ControllersWarmup.kt
  src/main/kotlin/it/pagopa/wallet/warmup/annotations/WarmupFunction.kt
  src/main/kotlin/it/pagopa/wallet/warmup/exceptions/WarmUpException.kt
  src/main/kotlin/it/pagopa/wallet/warmup/utils/WarmupUtils.kt
Labels: chart-minor, minor
