Repository pagopa/pagopa-wallet-service, pull requests merged in 2024-10, with the labels that each got.

#188 fix: CHK-3294 disable retry order-build
  api-tests/wallet_local_cards.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#189 fix: CHK-3294 Update api test no idempotency for post wallet/:id/sessions
  api-tests/wallet_local_paypal.collection.tests.json
Labels: size/small

#192 chore: scale-up wallet min instances
  helm/pay-wallet-values-prod.yaml
Labels: size/small, chart-patch, skip-release

#191 feat: remove unused update wallet last usage logic
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/Client.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Client.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/warmup/utils/WarmupUtils.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/config/SerializationConfigurationTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor

#193 chore: [CHK-3337] - remove last usage api tests
  api-tests/wallet_local_cards.collection.tests.json
Labels: size/small, ignore-for-release

#190 Feat [CHK-3292] Log the orderId during the onboarding phase in the wallet-log-events collection.
  src/main/kotlin/it/pagopa/wallet/audit/AuditWallet.kt
  src/main/kotlin/it/pagopa/wallet/audit/LoggingEvent.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor
