Repository pagopa/pagopa-wallet-service, pull requests merged in 2024-04, with the labels that each got.

#123 fix helm config values for uat
  helm/values-uat.yaml
Labels: size/small

#126 [CHK-2700] Align wallet-api specs to openapi for appIO infra
  api-spec/wallet-api.yaml
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, patch, chart-patch

#124 [CHK-2681] Setup OTeL agent
  Dockerfile
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/reactormdc/ConfigurationContextLifterMDC.kt
  src/main/kotlin/it/pagopa/wallet/reactormdc/ContextLifterMDC.kt
  src/main/resources/logback-spring.xml
Labels: size/small, patch, chart-patch

#125 feat: APM api key mapping
  .env.example
  .env.local
  docker/config/npg-mock/middleware.js
  helm/values-dev.yaml
  helm/values-uat.yaml
  npg-api/npg-api.yaml
  src/main/kotlin/it/pagopa/wallet/client/NpgClient.kt
  src/main/kotlin/it/pagopa/wallet/config/NpgApiKeyConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/config/OnboardingConfig.kt
  src/main/kotlin/it/pagopa/wallet/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/wallet/exception/NpgApiKeyConfigurationException.kt
  src/main/kotlin/it/pagopa/wallet/exception/NpgApiKeyMissingPspRequestedException.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/npg/NpgPspApiKeysConfig.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/client/NpgClientTest.kt
  src/test/kotlin/it/pagopa/wallet/config/WebClientConfigTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/npg/NpgPspApiKeysConfigTest.kt
  src/test/resources/application.test.properties
Labels: size/large

#127 fix: add missing uat env variable
  helm/values-uat.yaml
Labels: size/small

#128 [CHK-2722] Filter get wallets by userId filtering by VALIDATED status
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_paypal.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/repositories/WalletRepository.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor

#129 [CHK-2682] Improve migration logging
  src/main/kotlin/it/pagopa/wallet/reactormdc/ConfigurationContextLifterMDC.kt
  src/main/kotlin/it/pagopa/wallet/reactormdc/ContextLifterMDC.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
Labels: size/small, patch, chart-patch

#131 [CHK-2665] feat(security): check user id in all wallet CRUD and onboarding api calls implementation
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_migration.collection.tests.json
  api-tests/wallet_local_paypal.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor

#130 [CHK-2577] Wallet last usage internal API
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/Wallet.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletApplicationMetadata.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/document/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/WalletTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, patch, chart-patch

#133 [CHK-2713] Expose last usage through GET Wallet
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/domain/wallets/WalletApplication.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small, chart-minor, minor

#135 [CHK-2755] Add dedicated CSTAR api key for migration tests
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
Labels: size/small

#136 [CHK-2578] A contract id hmac as log MDC and Trace attribute
  api-spec/wallet-api.yaml
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/util/Tracing.kt
Labels: size/small

#134 [CHK-2752] add userId checking in post validation
  api-spec/wallet-api.yaml
  helm/values-dev.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
Labels: size/small

#138 [CHK-2678] refactor(brand): refactor card brand handling and remap NPG's `MC` to `MASTERCARD`
  src/main/kotlin/it/pagopa/wallet/config/LogoConfig.kt
  src/main/kotlin/it/pagopa/wallet/controllers/MigrationController.kt
  src/main/kotlin/it/pagopa/wallet/documents/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/CardBrand.kt
  src/main/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetails.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/WalletUtils.kt
  src/test/kotlin/it/pagopa/wallet/WalletTestUtils.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardBrandTest.kt
  src/test/kotlin/it/pagopa/wallet/domain/wallets/details/CardDetailsTest.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/WalletUtilsTest.kt
Labels: size/small

#139 [CHK-2777] Add check to prevent onboarding of same payment gateway id
  api-tests/wallet_local_migration.collection.tests.json
  src/main/kotlin/it/pagopa/wallet/exception/MigrationError.kt
  src/main/kotlin/it/pagopa/wallet/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/wallet/services/MigrationService.kt
  src/test/kotlin/it/pagopa/wallet/services/MigrationServiceTest.kt
Labels: size/small

#141 chore(conf): add mooney as required psp for paypal
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release
