Repository pagopa/pagopa-wallet-service, pull requests merged in 2025-07, with the labels that each got.

#230 feat: [CHK-4207] update to java 21
  .devops/pay-wallet-code-review-pipelines.yml
  Dockerfile
  build.gradle.kts
Labels: size/small, chart-minor, minor

#226 [CHK-4277] feat(api-key): add api key verification
  .env.example
  .env.local
  README.md
  api-spec/wallet-api.yaml
  api-tests/wallet_local_cards.collection.tests.json
  api-tests/wallet_local_cards.environment.json
  api-tests/wallet_local_migration.collection.tests.json
  api-tests/wallet_local_migration.environment.json
  api-tests/wallet_local_paypal.collection.tests.json
  api-tests/wallet_local_paypal.environment.json
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
  src/main/kotlin/it/pagopa/wallet/controllers/TransactionWalletController.kt
  src/main/kotlin/it/pagopa/wallet/controllers/WalletController.kt
  src/main/kotlin/it/pagopa/wallet/util/ApiKeyFilter.kt
  src/main/kotlin/it/pagopa/wallet/warmup/utils/WarmupUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/wallet/controllers/ApplicationsControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/MigrationControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/TransactionWalletControllerTest.kt
  src/test/kotlin/it/pagopa/wallet/controllers/WalletControllerTest.kt
  src/test/resources/application.test.properties
Labels: size/large

#232 chore: increase memory limits
  helm/pay-wallet-values-prod.yaml
Labels: size/small, patch, chart-patch

#235 [PIDM-823] Revert "chore(mongo): add replica set to mongo connection string (#223)"
  README.md
  helm/pay-wallet-values-prod.yaml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch

#236 [PIDM-826] feat(redis): migrate to standard redis
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, patch, chart-patch

#237 chore(reactive-redis): PIDM-816 reactive redis template
  src/main/kotlin/it/pagopa/wallet/config/RedisConfiguration.kt
  src/main/kotlin/it/pagopa/wallet/repositories/NpgSessionsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/repositories/PaymentMethodsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/repositories/ReactiveRedisTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/repositories/RedisTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/repositories/UniqueIdTemplateWrapper.kt
  src/main/kotlin/it/pagopa/wallet/services/PaymentMethodsService.kt
  src/main/kotlin/it/pagopa/wallet/services/WalletService.kt
  src/main/kotlin/it/pagopa/wallet/util/UniqueIdUtils.kt
  src/test/kotlin/it/pagopa/wallet/repositories/ReactiveRedisTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/wallet/services/PaymentMethodsServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/services/WalletServiceTest.kt
  src/test/kotlin/it/pagopa/wallet/util/converters/mongo/UniqueIdUtilTest.kt
Labels: size/small, chart-minor, minor
