Repository pagopa/pagopa-wallet-service, pull requests merged in 2025-02, with the labels that each got.

#203 [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions
  .devops/pay-wallet-code-review-pipelines.yml
Labels: size/small, ignore-for-release, skip-release

#204 chore: update github release task
  .devops/azure-templates/gradle-github-release.yml
Labels: size/small, patch, chart-patch

#205 chore: remove migration api tests
  .devops/azure-templates/api-tests.yml
  .devops/pay-wallet-deploy-pipelines.yml
Labels: size/small, ignore-for-release

#207 feat: upgrade to helm chart 7
  helm/Chart.lock
  helm/Chart.yaml
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
  helm/pay-wallet-values-uat.yaml
Labels: size/small, chart-minor, minor

#208 chore(helm): fix canary delivery parameters indentation
  helm/pay-wallet-values-dev.yaml
  helm/pay-wallet-values-prod.yaml
Labels: size/small, patch, chart-patch
